### PR TITLE
Fix #639: Append id to duplicate files with the same path

### LINKED ISSUE #639: Corruption when multiple files with the same filename and path are downloaded
I got a corrupt PDF when I tried to download this midterm-logistics.pdf file. There are two of them uploaded by the lecturer:

image

When I downloaded it, I got this weird corrupted PDF:

image

I lacked the foresight to save a copy of the actual corrupt PDF, but I'm thinking this is simply what happens when two parallel downloads go to the same location.

### PR DESCRIPTION
**Pull request by btzy**
- This is a temporary fix that isn't ideal, but definitely better than what we have now.

### CODE REVIEW

**Comment by angelsl** [comment]
What would an ideal fix be, though? :|

Maybe we can detect such conflicts and rename all files (or older files) with some sort of nonce (maybe the file's UUID)?

**Comment by btzy** [comment]
> Maybe we can detect such conflicts and rename all files (or older files) with some sort of nonce (maybe the file's UUID)?

Perhaps renaming just the older files with the nonce will make it more consistent with the existing update/rename behaviour, since the newest version of an updated file always has no suffix currently.  There may be a rare situation where the newest file is subsequently deleted, in which case the file on the local machine with no suffix would now refer to a deleted file (which could perhaps contain erroneous information that the lecturer is trying to remove).

**Comment by btzy** [comment]
@angelsl Can we merge this soon?  I might lose access to the test case on Luminus soon...

**Comment by angelsl** [comment]
Looks good to me, I think. (Can't really test it, of course..)

**Review by angelsl — APPROVED** [review]

**Pull request merged**
