### PR TITLE
Retrieve modules in future terms too

### PR DESCRIPTION
**Pull request by btzy**
Not sure if you like this, but it brings the behaviour closer to how Luminus seems to behave, and also what users would expect.

We're comparing strings here, but assuming NUS sticks with the currently-used semester identifiers, string ordering is equivalent to chronological ordering.

### CODE REVIEW

**Comment by angelsl** [comment]
How about this?

```rs
pub async fn modules(&self, term: Option<String>) -> Result<Vec<Module>> {
  enum FilterMode {
      GreaterThan(String),
      Equal(String),
  }
  let filter = if let Some(term) = term {
      FilterMode::Equal(term)
  } else {
      FilterMode::GreaterThan(self.current_term().await?)
  };

  let modules = self
      .api_as_json::<ApiData>("module", Method::GET, None)
      .await?;

  if let Data::Modules(modules) = modules.data {
      Ok(modules
          .into_iter()
          .filter(|m| match &filter {
              FilterMode::Equal(term) => m.term == *term,
              FilterMode::GreaterThan(term) => m.term >= *term,
          })
          .collect())
  } else if let Data::Empty(_) = modules.data {
      Ok(vec![])
  } else {
      Err("Invalid API response from server: type mismatch")
  }
}
```

**Comment by btzy** [comment]
Yeah, seems better given the other PR that allows the user to specify the term.

**Comment by btzy** [comment]
Updated the commit.  I put the `match` outside the filter because it didn't feel right otherwise... though it probably doesn't matter.

**Review by angelsl — APPROVED** [review]
Looks good!

**Pull request merged**
